### ISSUE TITLE
use TOC on side

### ISSUE THREAD

**Issue by prishs** [Wonderfall/hugo-WonderMod#5]
as papermod doesn't have support for sidebar toc.. i downloaded this module to see how sidebar toc looks.
but it was showing normal toc only.. even on example site it is normal toc.

how to use toc in this upgraded theme? do i have to use any other parameter.

**Comment by Wonderfall** [comment]
Side TOC only appears on large enough displays. You can probably tweak the CSS value there if you're not satisfied with how I've compromised it:

https://github.com/Wonderfall/hugo-WonderMod/blob/master/assets/css/common/post-single.css#L274

**Comment by prishs** [comment]
ok.. thanks.. will give it a try..
