### ISSUE TITLE
[BUG] Page's metadata rendering broken.

### ISSUE THREAD

**Issue by storopoli** [Wonderfall/hugo-WonderMod#6]
Hugo v0.120 introduced something that broke page's metadata like date and author:
<img width="734" alt="image" src="https://github.com/Wonderfall/hugo-WonderMod/assets/43353831/54fb544c-38b2-40f7-b717-fae4b542374f">

This was reported in the original PaperMod theme (https://github.com/adityatelange/hugo-PaperMod/issues/1325)
and fixed in this commit (https://github.com/adityatelange/hugo-PaperMod/commit/7795c90f6fa106733267481d9ed0518b00f2c62c).

I think that to solve this issue either:

- Rebase to the latest PaperMod
- add a `| safeHTML` to the `delimit` parameter in `layouts/partials/post_meta.html`

**Comment by Wonderfall** [comment]
Thanks for reporting. I'll take a look ASAP!

**Comment by Andreapm1977** [comment]
thanks! adding it to both post_meta.html and author.html saved my life!

**Comment by storopoli** [comment]
Yes, but it should be solved in WonderMod with a careful rebase to PaperMod.

**Comment by d4rklynk** [comment]
This is expected: https://github.com/gohugoio/hugo/issues/11647

**Comment by d4rklynk** [comment]
And FYI, just in case: https://github.com/gohugoio/hugo/issues/11455

**Comment by storopoli** [comment]
> And FYI, just in case: [gohugoio/hugo#11455](https://github.com/gohugoio/hugo/issues/11455)

![image](https://github.com/Wonderfall/hugo-WonderMod/assets/43353831/c9e08fed-6835-4578-90a3-3b83ee33f484)

**Comment by Wonderfall** [comment]
Should be fixed now.

**Comment by storopoli** [comment]
Thank you!
